### ISSUE TITLE
Sniffing - Operation not permitted

### ISSUE THREAD

**Issue by bagges** [robertbeal/docker-dasshio#8]
I think the problem is because the dasshio user has not enough rights to start sniffing. I tried with cap_add: ALL, but still the same. How did you got arround this?

### docker-compose.yml
```
version: '3.3'

services:

  dasshio:
    container_name: dasshio
    image: robertbeal/dasshio:latest
    network_mode: host
#    cap_add:
#      - ALL
    restart: unless-stopped
```

### Log
```
Starting dasshio ... done
Attaching to dasshio
dasshio    | 2020-07-18 09:46:23,658 | INFO | Reading config file: /data/options.json
dasshio    | 2020-07-18 09:46:23,659 | INFO | Starting...
dasshio    | 2020-07-18 09:46:23,659 | INFO | Starting sniffing...
dasshio    | 2020-07-18 09:46:23,659 | WARNING | OS error: [Errno 1] Operation not permitted
```
